name: Build and deploy site

on:
  pull_request:
  push:
    branches:
    - src
  workflow_dispatch:

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest

    env:
      DEPLOY: ${{ github.event_name != 'pull_request' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Should I deploy ${{ env.DEPLOY }}
      run: |
        - echo ${{ env.DEPLOY }}
        - echo ${{ github.event_name }}
    - name: Build and Deploy Nikola ${{ env.DEPLOY }}
      uses: getnikola/nikola-action@v4
      with:
        dry_run: true
